### ISSUE TITLE
give me discvord invite 🥺 

### ISSUE THREAD

**Issue by your-bestie** [KDot227/Batch-Token-Grabber#3]
discord is 🤡

**Comment by timmywag2** [comment]
godfather oasis? or cheataway (not made yet)

**Comment by your-bestie** [comment]
i found it cuz youre slow smfh

**Comment by timmywag2** [comment]
i responded after 30 seconds 💀

**Comment by your-bestie** [comment]
nolife fat timmy

**Comment by your-bestie** [comment]
i mean
tyvm

**Comment by timmywag2** [comment]
stfu u dumb faggot

**Comment by timmywag2** [comment]
wait will i get banend for that

**Comment by your-bestie** [comment]
idk i tell ppl ima rape them and to kill themselves and that theyre niggers all the time

**Comment by timmywag2** [comment]
fuck the jews, 😡

**Comment by your-bestie** [comment]
God save the nazis

**Comment by timmywag2** [comment]
[click me plz](https://media.discordapp.net/attachments/790269743403106347/990631414548533289/image0.gif)
